### ISSUE TITLE
go-cs always uses `ssh -i`, even if not specified by the user

### ISSUE THREAD

**Issue by n-st** [akosela/go-cs#2]
The argument parser uses `~/.ssh/id_rsa` as the default for the identity file (https://github.com/akosela/go-cs/blob/master/cs/cs.go#L426-L427), so it is passed to SSH even if the user did not specify `cs -i ...` on the commandline.

Proposal: Use a null value as the default and do not pass `-i` to ssh if that null value was not overridden by a `cs` commandline argument?

**Comment by akosela** [comment]
Fixed in `b63cf55eade090dc53d6f9870a6008fb238c471c`
